# Serching Engine Optimisation
__Author__: Jingkai (Kyle) Sun

__Description__: SEO of Tencent News App

# Feature Extraction

In [1]:
import numpy as np
import pandas as pd

In [2]:
#loading the Boston Dataset
data = pd.read_csv('/Users/kyle/Documents/Virtual_Intern/Tencent/data/words.csv', low_memory=False)
df_raw = pd.DataFrame(data)

In [3]:
df_raw['label_binary'] = np.ones(len(df_raw))

In [4]:
df_raw

        label   qid                                  title  label_binary
0           5  g5高速           G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！           1.0
1           5  g5高速            G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米           1.0
2           5  g5高速           12月起，G5京昆高速开始“冬管”，这些地方需特别注意！           1.0
3           4  g5高速          G5O沪渝高速部分路段进行对接施工，这些车辆全天禁止通行！           1.0
4           5  g5高速                 G5京昆高速因大雪、路面结冰，继续交通管制！           1.0
...       ...   ...                                    ...           ...
413347      3  赤脚医生  还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖           1.0
413348      2  赤脚医生                             赤脚医生和她的小背篓           1.0
413349      2  赤脚医生                             情洒杏林路的赤脚医生           1.0
413350      3  赤脚医生                    邯郸冀南新区赤脚医生补助名单正在审核中           1.0
413351      3  赤脚医生                 疑似传播HIV病毒 印度一名“赤脚医生”被捕           1.0

[413352 rows x 4 columns]

In [5]:
df_raw['label_binary'][df_raw['label'] <=3] = 0

/Users/kyle/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [6]:
df_raw = df_raw[df_raw['label'] != 4]
df_raw = df_raw.reset_index()
df_raw

,index,label,qid,title,label_binary
0,0,5,g5高速,G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！,1.0
1,1,5,g5高速,G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米,1.0
2,2,5,g5高速,12月起，G5京昆高速开始“冬管”，这些地方需特别注意！,1.0
3,4,5,g5高速,G5京昆高速因大雪、路面结冰，继续交通管制！,1.0
4,5,5,g5高速,G5京昆高速结冰严重，栗子坪至彝海双向交通管制！,1.0
...,...,...,...,...,...
332629,413347,3,赤脚医生,还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖,0.0
332630,413348,2,赤脚医生,赤脚医生和她的小背篓,0.0
332631,413349,2,赤脚医生,情洒杏林路的赤脚医生,0.0
332632,413350,3,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,0.0
332633,413351,3,赤脚医生,疑似传播HIV病毒 印度一名“赤脚医生”被捕,0.0

# Data Balance

In [7]:
print(len(df_raw[df_raw['label_binary'] ==0 ]))
print(len(df_raw[df_raw['label_binary'] ==1 ]))

190526
142108

In [8]:
# df_raw['label'] = df_raw['label'][df_raw['label'] != 0]
# df_raw[df_raw['label'] == 0]

In [9]:
# label_1 = df_raw[df_raw['label'] == 1]
# label_2 = df_raw[df_raw['label'] == 2]
# label_3 = df_raw[df_raw['label'] == 3]
# label_4 = df_raw[df_raw['label'] == 4]
# label_5 = df_raw[df_raw['label'] == 5]

In [10]:
# print(len(label_1) / len(df_raw) * 100)
# print(len(label_2) / len(df_raw) * 100)
# print(len(label_3) / len(df_raw) * 100)
# print(len(label_4) / len(df_raw) * 100)
# print(len(label_5) / len(df_raw) * 100)

In [11]:
# percentage_2 = len(label_1)/ float(len(label_2))
# percentage_3 = len(label_1)/ float(len(label_3))
# percentage_4 = len(label_1)/ float(len(label_4))
# percentage_5 = len(label_1)/ float(len(label_5))

# label_1_clean = label_1
# label_2_clean = label_2.sample(frac = percentage_2, random_state = 1)
# label_3_clean = label_3.sample(frac =percentage_3, random_state = 1)
# label_4_clean = label_4.sample(frac =percentage_4, random_state = 1)
# label_5_clean = label_5.sample(frac =percentage_5, random_state = 1)

# df = label_1_clean.append(label_2_clean)
# df = df.append(label_3_clean)
# df = df.append(label_4_clean)
# df = df.append(label_5_clean)
# df = df.sample(frac = 1)
# df = df.reset_index()
# df

In [12]:
# print(len(label_1_clean) / len(df) * 100)
# print(len(label_2_clean) / len(df) * 100)
# print(len(label_3_clean) / len(df) * 100)
# print(len(label_4_clean) / len(df) * 100)
# print(len(label_5_clean) / len(df) * 100)

In [8]:
df = df_raw
df

,index,label,qid,title,label_binary
0,0,5,g5高速,G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！,1.0
1,1,5,g5高速,G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米,1.0
2,2,5,g5高速,12月起，G5京昆高速开始“冬管”，这些地方需特别注意！,1.0
3,4,5,g5高速,G5京昆高速因大雪、路面结冰，继续交通管制！,1.0
4,5,5,g5高速,G5京昆高速结冰严重，栗子坪至彝海双向交通管制！,1.0
...,...,...,...,...,...
332629,413347,3,赤脚医生,还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖,0.0
332630,413348,2,赤脚医生,赤脚医生和她的小背篓,0.0
332631,413349,2,赤脚医生,情洒杏林路的赤脚医生,0.0
332632,413350,3,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,0.0
332633,413351,3,赤脚医生,疑似传播HIV病毒 印度一名“赤脚医生”被捕,0.0

In [9]:
# df = df.reset_index()
# df = df.drop(['index'], axis = 1)
df

,index,label,qid,title,label_binary
0,0,5,g5高速,G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！,1.0
1,1,5,g5高速,G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米,1.0
2,2,5,g5高速,12月起，G5京昆高速开始“冬管”，这些地方需特别注意！,1.0
3,4,5,g5高速,G5京昆高速因大雪、路面结冰，继续交通管制！,1.0
4,5,5,g5高速,G5京昆高速结冰严重，栗子坪至彝海双向交通管制！,1.0
...,...,...,...,...,...
332629,413347,3,赤脚医生,还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖,0.0
332630,413348,2,赤脚医生,赤脚医生和她的小背篓,0.0
332631,413349,2,赤脚医生,情洒杏林路的赤脚医生,0.0
332632,413350,3,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,0.0
332633,413351,3,赤脚医生,疑似传播HIV病毒 印度一名“赤脚医生”被捕,0.0

# Feature Engineering

In [10]:
#Feature Engineering
import string
def remove_punctuation(text):
    try: # python 2.x
        text = text.translate(None, string.punctuation)
    except: # python 3.x
        translator = text.maketrans('', '', '，？！《》.。、“”-+*/：……（）@:"＂,’‘— ')
        text = text.translate(translator)
    return text

In [11]:
# df = df.drop(['qid_clean', 'title_clean'], axis = 1)
# df

In [12]:
df['qid_clean'] = df['qid'].apply(remove_punctuation).replace(' ','').str.strip()

,index,label,qid,title,label_binary,qid_clean
0,0,5,g5高速,G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！,1.0,g5高速
1,1,5,g5高速,G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米,1.0,g5高速
2,2,5,g5高速,12月起，G5京昆高速开始“冬管”，这些地方需特别注意！,1.0,g5高速
3,4,5,g5高速,G5京昆高速因大雪、路面结冰，继续交通管制！,1.0,g5高速
4,5,5,g5高速,G5京昆高速结冰严重，栗子坪至彝海双向交通管制！,1.0,g5高速
...,...,...,...,...,...,...
332629,413347,3,赤脚医生,还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖,0.0,赤脚医生
332630,413348,2,赤脚医生,赤脚医生和她的小背篓,0.0,赤脚医生
332631,413349,2,赤脚医生,情洒杏林路的赤脚医生,0.0,赤脚医生
332632,413350,3,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,0.0,赤脚医生
332633,413351,3,赤脚医生,疑似传播HIV病毒 印度一名“赤脚医生”被捕,0.0,赤脚医生

In [13]:
# Remove punctuation for title
df['title_clean'] = df['title'].apply(remove_punctuation).replace(' ','').str.strip()
df

,index,label,qid,title,label_binary,qid_clean,title_clean
0,0,5,g5高速,G5京昆高速，瓦厂坪大桥路段山体险情，建议大家推迟出行！,1.0,g5高速,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行
1,1,5,g5高速,G5京昆高速雅西段拖乌山突降暴雪 部分路段积雪深达1米,1.0,g5高速,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米
2,2,5,g5高速,12月起，G5京昆高速开始“冬管”，这些地方需特别注意！,1.0,g5高速,12月起G5京昆高速开始冬管这些地方需特别注意
3,4,5,g5高速,G5京昆高速因大雪、路面结冰，继续交通管制！,1.0,g5高速,G5京昆高速因大雪路面结冰继续交通管制
4,5,5,g5高速,G5京昆高速结冰严重，栗子坪至彝海双向交通管制！,1.0,g5高速,G5京昆高速结冰严重栗子坪至彝海双向交通管制
...,...,...,...,...,...,...,...
332629,413347,3,赤脚医生,还记得H7N9吗？绍兴“赤脚医生”李兰娟领衔完成的项目获国家科技进步特等奖,0.0,赤脚医生,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖
332630,413348,2,赤脚医生,赤脚医生和她的小背篓,0.0,赤脚医生,赤脚医生和她的小背篓
332631,413349,2,赤脚医生,情洒杏林路的赤脚医生,0.0,赤脚医生,情洒杏林路的赤脚医生
332632,413350,3,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,0.0,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中
332633,413351,3,赤脚医生,疑似传播HIV病毒 印度一名“赤脚医生”被捕,0.0,赤脚医生,疑似传播HIV病毒印度一名赤脚医生被捕

In [14]:
df = df.drop(["qid",'title'], axis = 1)
df['qid_clean'] = df['qid_clean'].apply(lambda x: x.upper())
df['title_clean'] = df['title_clean'].apply(lambda x: x.upper())
# df

In [15]:
#分组id
df['group_id'] = df.groupby('qid_clean').ngroup().add(1)

In [17]:
df = df.drop(['index'], axis = 1)
df

,label,label_binary,qid_clean,title_clean,group_id
0,5,1.0,G5高速,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行,893
1,5,1.0,G5高速,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米,893
2,5,1.0,G5高速,12月起G5京昆高速开始冬管这些地方需特别注意,893
3,5,1.0,G5高速,G5京昆高速因大雪路面结冰继续交通管制,893
4,5,1.0,G5高速,G5京昆高速结冰严重栗子坪至彝海双向交通管制,893
...,...,...,...,...,...
332629,3,0.0,赤脚医生,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖,16088
332630,2,0.0,赤脚医生,赤脚医生和她的小背篓,16088
332631,2,0.0,赤脚医生,情洒杏林路的赤脚医生,16088
332632,3,0.0,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,16088
332633,3,0.0,赤脚医生,疑似传播HIV病毒印度一名赤脚医生被捕,16088

In [19]:
df.to_csv('queries_doc.csv', index = False)

In [23]:
import jieba.analyse as anls
import jieba
def words_extract(sentence, cut_type = 'cut'):
    if cut_type == 'cut':
        tot_terms = []
        for i in sentence:
            seg = jieba.lcut(i, cut_all = False)
            tot_terms.append(seg)
    elif cut_type == 'search':
        tot_terms = []
        for i in sentence:
            seg = jieba.lcut_for_search(i)
            tot_terms.append(seg)
    return tot_terms

In [24]:
#Cut words in qid_clean
# df = df.drop(['qid_terms'], axis =1)
df['qid_terms'] = words_extract(df['qid_clean'], cut_type = 'cut')
df

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/pf/pypg0m0x0ng1g1w1mhrbr2cm0000gn/T/jieba.cache
Loading model cost 0.692 seconds.
Prefix dict has been built successfully.

,index,label,label_binary,qid_clean,title_clean,group_id,qid_terms
0,0,5,1.0,G5高速,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行,893,"[G5, 高速]"
1,1,5,1.0,G5高速,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米,893,"[G5, 高速]"
2,2,5,1.0,G5高速,12月起G5京昆高速开始冬管这些地方需特别注意,893,"[G5, 高速]"
3,4,5,1.0,G5高速,G5京昆高速因大雪路面结冰继续交通管制,893,"[G5, 高速]"
4,5,5,1.0,G5高速,G5京昆高速结冰严重栗子坪至彝海双向交通管制,893,"[G5, 高速]"
...,...,...,...,...,...,...,...
332629,413347,3,0.0,赤脚医生,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖,16088,[赤脚医生]
332630,413348,2,0.0,赤脚医生,赤脚医生和她的小背篓,16088,[赤脚医生]
332631,413349,2,0.0,赤脚医生,情洒杏林路的赤脚医生,16088,[赤脚医生]
332632,413350,3,0.0,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,16088,[赤脚医生]
332633,413351,3,0.0,赤脚医生,疑似传播HIV病毒印度一名赤脚医生被捕,16088,[赤脚医生]

In [25]:
#Cut words in title_clean
df['title_terms'] = words_extract(df['title_clean'], cut_type = 'cut')
df

,index,label,label_binary,qid_clean,title_clean,group_id,qid_terms,title_terms
0,0,5,1.0,G5高速,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行,893,"[G5, 高速]","[G5, 京昆, 高速, 瓦厂, 坪, 大桥路, 段, 山体, 险情, 建议, 大家, 推迟..."
1,1,5,1.0,G5高速,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米,893,"[G5, 高速]","[G5, 京昆, 高速, 雅, 西段, 拖, 乌山, 突降, 暴雪, 部分, 路段, 积雪,..."
2,2,5,1.0,G5高速,12月起G5京昆高速开始冬管这些地方需特别注意,893,"[G5, 高速]","[12, 月, 起, G5, 京昆, 高速, 开始, 冬管, 这些, 地方, 需, 特别, 注意]"
3,4,5,1.0,G5高速,G5京昆高速因大雪路面结冰继续交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 因, 大雪, 路面, 结冰, 继续, 交通管制]"
4,5,5,1.0,G5高速,G5京昆高速结冰严重栗子坪至彝海双向交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 结冰, 严重, 栗子, 坪, 至, 彝海, 双向, 交通管制]"
...,...,...,...,...,...,...,...,...
332629,413347,3,0.0,赤脚医生,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖,16088,[赤脚医生],"[还, 记得, H7N9, 吗, 绍兴, 赤脚医生, 李兰娟, 领衔, 完成, 的, 项目,..."
332630,413348,2,0.0,赤脚医生,赤脚医生和她的小背篓,16088,[赤脚医生],"[赤脚医生, 和, 她, 的, 小, 背篓]"
332631,413349,2,0.0,赤脚医生,情洒杏林路的赤脚医生,16088,[赤脚医生],"[情洒, 杏林, 路, 的, 赤脚医生]"
332632,413350,3,0.0,赤脚医生,邯郸冀南新区赤脚医生补助名单正在审核中,16088,[赤脚医生],"[邯郸, 冀南, 新区, 赤脚医生, 补助, 名单, 正在, 审核, 中]"
332633,413351,3,0.0,赤脚医生,疑似传播HIV病毒印度一名赤脚医生被捕,16088,[赤脚医生],"[疑似, 传播, HIV, 病毒, 印度, 一名, 赤脚医生, 被捕]"

In [26]:
#Compute the number of words cut for qid and title
df = df.drop(["qid_clean"], axis = 1)
df['num_qid_terms'] = df["qid_terms"].apply(lambda s: len(s))
df['num_title_terms'] = df["title_terms"].apply(lambda s: len(s))

In [27]:
def num_matches(terms_a, terms_b):
    match_density = 0
    times = 0
    for i in terms_a:
        for j in terms_b:
            if i == j:
                times += 1
    return times

In [28]:
tot_num_matches = []
for i in range(len(df)):
    tot_num_matches.append(num_matches(df['qid_terms'][i],df['title_terms'][i]))
len(tot_num_matches)

332634

In [29]:
#Feature 1: Number of matched words in title
df['tot_num_matches'] = tot_num_matches
# df[0:10]

In [30]:
#Feature 2: The ratio between #of qid terms and #of meatched words in title
df['match_ratios'] = np.array(df['tot_num_matches']) * 1. / np.array(df['num_qid_terms'])
# df[0:10]

In [31]:
df[60:120]

,index,label,label_binary,title_clean,group_id,qid_terms,title_terms,num_qid_terms,num_title_terms,tot_num_matches,match_ratios
60,70,3,0.0,头套玩狗教你洗澡这位肌肉小哥很会玩,895,"[GAY, 帅哥, 写真]","[头套, 玩狗教, 你, 洗澡, 这位, 肌肉, 小哥, 很会, 玩]",3,9,0,0.000000
61,71,3,0.0,游泳体育生肌肉身材惹人口水種下自己的小哥谁来收获,895,"[GAY, 帅哥, 写真]","[游泳, 体育, 生, 肌肉, 身材, 惹, 人口, 水種, 下, 自己, 的, 小哥, 谁...",3,15,0,0.000000
62,72,3,0.0,赤身打鼓还是秀肉这个小哥视频被疯转,895,"[GAY, 帅哥, 写真]","[赤身, 打鼓, 还是, 秀肉, 这个, 小哥, 视频, 被, 疯转]",3,9,0,0.000000
63,73,3,0.0,蔡依林御用舞男肌肉私照很精彩,895,"[GAY, 帅哥, 写真]","[蔡依林, 御用, 舞男, 肌肉, 私照, 很, 精彩]",3,7,0,0.000000
64,75,1,0.0,单身狗看过来盛世美颜BLUED颜值一哥你心动了吗,896,[GBLIVE],"[单身, 狗, 看, 过来, 盛世, 美颜, BLUED, 颜值, 一哥, 你, 心动, 了...",1,13,0,0.000000
65,76,1,0.0,网盘里的那些国产网红你有几个,896,[GBLIVE],"[网盘, 里, 的, 那些, 国产, 网红, 你, 有, 几个]",1,9,0,0.000000
66,77,3,0.0,这些城市GDP超万亿万亿是什么概念,897,"[GDP, 是, 什么]","[这些, 城市, GDP, 超, 万亿, 万亿, 是, 什么, 概念]",3,9,3,1.000000
67,78,3,0.0,中等收入陷阱是什么意思是指人均GDP在多少,897,"[GDP, 是, 什么]","[中等, 收入, 陷阱, 是, 什么, 意思, 是, 指, 人均, GDP, 在, 多少]",3,12,4,1.333333
68,79,3,0.0,你知道什么是EGDP吗,897,"[GDP, 是, 什么]","[你, 知道, 什么, 是, EGDP, 吗]",3,6,2,0.666667
69,80,1,0.0,生活服务业占GDP516％成为经济增长新引擎聊聊新零售的趋势和商业本质到底是什么,897,"[GDP, 是, 什么]","[生活, 服务业, 占, GDP516, ％, 成为, 经济, 增长, 新, 引擎, 聊聊,...",3,21,2,0.666667
70,81,3,0.0,周小川答记者问提到的GDP平减指数是什么概念,897,"[GDP, 是, 什么]","[周小川, 答记者问, 提到, 的, GDP, 平减, 指数, 是, 什么, 概念]",3,10,3,1.000000
71,82,3,0.0,刘陵龙1221黄金涨破位了后市还会涨吗GDP数据是什么,897,"[GDP, 是, 什么]","[刘陵龙, 1221, 黄金, 涨破位, 了, 后市, 还会涨, 吗, GDP, 数据, 是...",3,12,3,1.000000
72,83,3,0.0,非星级酒店不受理投诉旅发委是干啥的GDP,897,"[GDP, 是, 什么]","[非, 星级, 酒店, 不, 受理, 投诉, 旅发委是, 干, 啥, 的, GDP]",3,11,1,0.333333
73,84,3,0.0,72年前美国GDP占世界一半美军强大背后的死穴是啥,897,"[GDP, 是, 什么]","[72, 年前, 美国, GDP, 占, 世界, 一半, 美军, 强大, 背后, 的, 死穴...",3,14,2,0.666667
74,85,2,0.0,14城突破万亿GDP但城市最珍贵的资源是什么,897,"[GDP, 是, 什么]","[14, 城, 突破, 万亿, GDP, 但, 城市, 最, 珍贵, 的, 资源, 是, 什么]",3,13,3,1.000000
75,86,3,0.0,极速评什么是GDP,897,"[GDP, 是, 什么]","[极速, 评, 什么, 是, GDP]",3,5,3,1.000000
76,88,3,0.0,GDP和GNP分别是什么意思,897,"[GDP, 是, 什么]","[GDP, 和, GNP, 分别, 是, 什么, 意思]",3,7,3,1.000000
77,89,3,0.0,7000亿GDP的东莞没啥牛的是每8人就有一个老板,897,"[GDP, 是, 什么]","[7000, 亿, GDP, 的, 东莞, 没, 啥, 牛, 的, 是, 每, 8, 人, ...",3,17,2,0.666667
78,90,3,0.0,温州各县市GDP与商品房销售量大比拼有什么关联排行前三的是,897,"[GDP, 是, 什么]","[温州, 各县市, GDP, 与, 商品房, 销售量, 大比拼, 有, 什么, 关联, 排行...",3,15,3,1.000000
79,91,3,0.0,这个县是江苏GDP最差城市中唯一百强县凭啥那么牛,897,"[GDP, 是, 什么]","[这个, 县, 是, 江苏, GDP, 最差, 城市, 中, 唯一, 百强县, 凭, 啥, ...",3,14,2,0.666667
80,92,3,0.0,生活在GDP两万亿城市是种什么感受,897,"[GDP, 是, 什么]","[生活, 在, GDP, 两, 万亿, 城市, 是, 种, 什么, 感受]",3,10,3,1.000000
81,94,2,0.0,贵州GDP增速领跑GDP增长对股市的影响是什么,897,"[GDP, 是, 什么]","[贵州, GDP, 增速, 领跑, GDP, 增长, 对, 股市, 的, 影响, 是, 什么]",3,12,4,1.333333
82,95,3,0.0,比GDP算什么一看人均收入我大广东竟被这个省PK下去,897,"[GDP, 是, 什么]","[比, GDP, 算, 什么, 一看, 人均收入, 我大, 广东, 竟, 被, 这个, 省,...",3,14,2,0.666667
83,96,3,0.0,徐州GDP连续攀升即将登顶北方第五城这背后的原因是什么,897,"[GDP, 是, 什么]","[徐州, GDP, 连续, 攀升, 即将, 登顶, 北方, 第五, 城, 这, 背后, 的,...",3,15,3,1.000000
84,97,2,0.0,中国14城GDP突破万亿但城市最珍贵的资源是啥,897,"[GDP, 是, 什么]","[中国, 14, 城, GDP, 突破, 万亿, 但, 城市, 最, 珍贵, 的, 资源, ...",3,14,2,0.666667
85,98,3,0.0,武汉经济加速奔跑GDP比上年增长8％是什么在驱动,897,"[GDP, 是, 什么]","[武汉, 经济, 加速, 奔跑, GDP, 比, 上年, 增长, 8, ％, 是, 什么, ...",3,14,3,1.000000
86,99,3,0.0,你是什么GDP,897,"[GDP, 是, 什么]","[你, 是, 什么, GDP]",3,4,3,1.000000
87,100,3,0.0,内蒙古数据调整对GDP可能产生什么影响,897,"[GDP, 是, 什么]","[内蒙古, 数据, 调整, 对, GDP, 可能, 产生, 什么, 影响]",3,9,2,0.666667
88,101,3,0.0,是什么带动了GDP超预期,897,"[GDP, 是, 什么]","[是, 什么, 带动, 了, GDP, 超, 预期]",3,7,3,1.000000
89,102,5,1.0,紧缩政策对中国2018年GDP有什么影响,897,"[GDP, 是, 什么]","[紧缩, 政策, 对, 中国, 2018, 年, GDP, 有, 什么, 影响]",3,10,2,0.666667
90,103,3,0.0,什么是GDP我用最简单的言辞解释给你听,897,"[GDP, 是, 什么]","[什么, 是, GDP, 我用, 最, 简单, 的, 言辞, 解释, 给, 你, 听]",3,12,3,1.000000
91,104,3,0.0,是什么原因让这5年河源GDP年均增长超全国平均水平,897,"[GDP, 是, 什么]","[是, 什么, 原因, 让, 这, 5, 年, 河源, GDP, 年均, 增长, 超, 全国...",3,14,3,1.000000
92,113,3,0.0,一周大事件全炫茂＆韩惠珍恋爱GD入伍吴达洙为性侵丑闻道歉,898,"[GD, 入伍]","[一周, 大, 事件, 全炫茂, ＆, 韩惠珍, 恋爱, GD, 入伍, 吴达洙, 为, 性...",2,14,2,1.000000
93,130,3,0.0,易烊千玺中戏复试顺利GD入伍获TOP全程互送,898,"[GD, 入伍]","[易, 烊, 千玺, 中戏, 复试, 顺利, GD, 入伍, 获, TOP, 全程, 互送]",2,12,2,1.000000
94,135,5,1.0,今年春节不收礼要送就送GEC环保币,899,[GEC],"[今年春节, 不, 收礼, 要, 送, 就, 送, GEC, 环保, 币]",1,10,1,1.000000
95,136,2,0.0,GEC轻量级多国语言推广社区测试版发布,899,[GEC],"[GEC, 轻量级, 多, 国, 语言, 推广, 社区, 测试版, 发布]",1,9,1,1.000000
96,137,5,1.0,GEC币可能是下一个风口,899,[GEC],"[GEC, 币, 可能, 是, 下, 一个, 风口]",1,7,1,1.000000
97,138,5,1.0,GEC将在今晚开启崭新的一页,899,[GEC],"[GEC, 将, 在, 今晚, 开启, 崭新, 的, 一页]",1,8,1,1.000000
98,139,3,0.0,只要你有才每天都有GEC平台送给你云矿机的机会,899,[GEC],"[只要, 你, 有, 才, 每天, 都, 有, GEC, 平台, 送给, 你, 云, 矿机,...",1,15,1,1.000000
99,140,5,1.0,GEC给了币圈一次大的震荡,899,[GEC],"[GEC, 给, 了, 币, 圈, 一次, 大, 的, 震荡]",1,9,1,1.000000
100,141,5,1.0,关于GEC的一些基本操作,899,[GEC],"[关于, GEC, 的, 一些, 基本操作]",1,5,1,1.000000
101,142,5,1.0,2018最新详细GEC交易视频手把手教会你快速学会交易,899,[GEC],"[2018, 最新, 详细, GEC, 交易, 视频, 手把手, 教会, 你, 快速, 学会...",1,12,1,1.000000
102,143,5,1.0,GEC环保币10大优势＋8大亮点,899,[GEC],"[GEC, 环保, 币, 10, 大, 优势, ＋, 8, 大, 亮点]",1,10,1,1.000000
103,144,5,1.0,GEC环保币大额交易担保8大步骤重要消息,899,[GEC],"[GEC, 环保, 币, 大额, 交易, 担保, 8, 大, 步骤, 重要, 消息]",1,11,1,1.000000
104,145,5,1.0,2018戌狗年新的开始GEC家人们如何不输在起跑线上,899,[GEC],"[2018, 戌狗, 年, 新, 的, 开始, GEC, 家, 人们, 如何, 不输, 在,...",1,14,1,1.000000
105,146,5,1.0,关于GEC的官方唯一宣传片赚钱了建议再看看,899,[GEC],"[关于, GEC, 的, 官方, 唯一, 宣传片, 赚钱, 了, 建议, 再, 看看]",1,11,1,1.000000
106,147,5,1.0,2018GEC中国区绿色城市评选结果,899,[GEC],"[2018GEC, 中国区, 绿色, 城市, 评选, 结果]",1,6,0,0.000000
107,148,5,1.0,也许你从未真正了解过GEC,899,[GEC],"[也许, 你, 从未, 真正, 了解, 过, GEC]",1,7,1,1.000000
108,149,5,1.0,GEC彩铃上线助力GEC事业新篇章,899,[GEC],"[GEC, 彩铃, 上线, 助力, GEC, 事业, 新篇章]",1,7,2,2.000000
109,150,5,1.0,现在GEC利润太低不要看一时之利要往远看,899,[GEC],"[现在, GEC, 利润, 太低, 不要, 看, 一时, 之利要, 往远, 看]",1,10,1,1.000000
110,151,3,0.0,教你如何找回和修改GEC密码,899,[GEC],"[教, 你, 如何, 找回, 和, 修改, GEC, 密码]",1,8,1,1.000000
111,152,3,0.0,学人之长补已之短增强信心参与GEC携手同行,899,[GEC],"[学人, 之长, 补, 已, 之, 短, 增强, 信心, 参与, GEC, 携手, 同行]",1,12,1,1.000000
112,153,5,1.0,GEC数字货币平台标杆安全长久稳定,899,[GEC],"[GEC, 数字, 货币, 平台, 标杆, 安全, 长久, 稳定]",1,8,1,1.000000
113,154,3,0.0,大矿机中矿机小矿机运行周期及收益预算GEC矿工2018必修课,899,[GEC],"[大矿, 机中, 矿机, 小, 矿机, 运行, 周期, 及, 收益, 预算, GEC, 矿工...",1,14,1,1.000000
114,155,5,1.0,所有GEC家人收好这份实实在在的大红包,899,[GEC],"[所有, GEC, 家人, 收, 好, 这份, 实实在在, 的, 大红包]",1,9,1,1.000000
115,156,3,0.0,1个GEC币最低100美元你准备好了吗,899,[GEC],"[1, 个, GEC, 币, 最低, 100, 美元, 你, 准备, 好了吗]",1,10,1,1.000000
116,157,5,1.0,加密数字货币的实名认证合法化GEC走在最前面,899,[GEC],"[加密, 数字, 货币, 的, 实名, 认证, 合法化, GEC, 走, 在, 最, 前面]",1,12,1,1.000000
117,158,2,0.0,GEC气候不断变化不同价值观如何影响人们心理适应,899,[GEC],"[GEC, 气候, 不断, 变化, 不同, 价值观, 如何, 影响, 人们, 心理, 适应]",1,11,1,1.000000
118,159,5,1.0,GEC环保币赚的钱是从哪里来的GEC到底是怎么赚钱的为什么只涨不跌呢,899,[GEC],"[GEC, 环保, 币, 赚, 的, 钱, 是从, 哪里, 来, 的, GEC, 到底, 是...",1,21,2,2.000000
119,160,5,1.0,GEC家人们来来来合种一棵我们的参天大树,899,[GEC],"[GEC, 家, 人们, 来来来, 合种, 一棵, 我们, 的, 参天大树]",1,9,1,1.000000

In [32]:
#Feature 3: 
import jieba.analyse as anlys
def get_tfidf(list1, sentence):
    store = anlys.extract_tags(sentence, topK = None, withWeight= True, allowPOS=(), withFlag=False)
    TFIDF = []
    for i in store:
        TFIDF.append(i)
    words_with_tfidf = dict(TFIDF)
    
    words_weight = []
    for i in list1:
        for j in words_with_tfidf.keys():
            if i == j:
                words_weight.append(words_with_tfidf[j])
    return sum(words_weight)

In [33]:
link = []
for i in range(len(df)):
    link.append(get_tfidf(df['qid_terms'][i], df['title_clean'][i]))
df['tfidf_score'] = link

In [34]:
# def get_textrank(list, sentence):
#     store = anls.textrank(sentence, topK=None, withWeight = True, allowPOS = ('ns', 'nl' , 'ng', 'vx','n', 'v', 'vn', 'vd', 'nr1', 'nr2'),withFlag=False)
#     textrank = []
#     for i in store:
#         textrank.append(i)
#     words_with_textrank = dict(textrank)

#     words_rank_weight = []
#     for i in list:
#         for j in words_with_textrank.keys():
#             if i == j:
#                 words_rank_weight.append(words_with_textrank[j])
#     return sum(words_rank_weight)

In [35]:
# link_textrank = []
# for i in range(len(df)):
#     link_textrank.append(get_textrank(df['qid_terms'][i], df['title_clean'][i]))
# df['textrank_score'] = link_textrank
# df

In [36]:
# Feature: match density
def match_density(list1, list2, density_threthold = 1):
    match_index = []
    count = 0
    for j in list2 :
        for i in list1:
            if j == i:
                match_index.append(list2.index(i))
                count += 1
    match_density = []
    for i in range(len(match_index)):
        try:
            if match_index[i+1] - match_index[i] <= density_threthold:
                match_density.append(1)
            else:
                match_density.append(0)
        except:
            break
    if match_density != [] :
    # return max(set(match_density), key=match_density.count)  # get mode
        return sum(match_density) * 1. / len(match_density)
    else :
        return 0

In [37]:
link_match_density = []
for i in range(len(df)):
    link_match_density.append(match_density(df['qid_terms'][i], df['title_terms'][i], 2))
df['match_density'] = link_match_density

In [38]:
df

,index,label,label_binary,title_clean,group_id,qid_terms,title_terms,num_qid_terms,num_title_terms,tot_num_matches,match_ratios,tfidf_score,match_density
0,0,5,1.0,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行,893,"[G5, 高速]","[G5, 京昆, 高速, 瓦厂, 坪, 大桥路, 段, 山体, 险情, 建议, 大家, 推迟...",2,13,2,1.0,1.685839,1.0
1,1,5,1.0,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米,893,"[G5, 高速]","[G5, 京昆, 高速, 雅, 西段, 拖, 乌山, 突降, 暴雪, 部分, 路段, 积雪,...",2,15,2,1.0,1.685839,1.0
2,2,5,1.0,12月起G5京昆高速开始冬管这些地方需特别注意,893,"[G5, 高速]","[12, 月, 起, G5, 京昆, 高速, 开始, 冬管, 这些, 地方, 需, 特别, 注意]",2,13,2,1.0,1.854423,1.0
3,4,5,1.0,G5京昆高速因大雪路面结冰继续交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 因, 大雪, 路面, 结冰, 继续, 交通管制]",2,9,2,1.0,2.318028,1.0
4,5,5,1.0,G5京昆高速结冰严重栗子坪至彝海双向交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 结冰, 严重, 栗子, 坪, 至, 彝海, 双向, 交通管制]",2,11,2,1.0,2.060470,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
332629,413347,3,0.0,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖,16088,[赤脚医生],"[还, 记得, H7N9, 吗, 绍兴, 赤脚医生, 李兰娟, 领衔, 完成, 的, 项目,...",1,15,1,1.0,1.074658,0.0
332630,413348,2,0.0,赤脚医生和她的小背篓,16088,[赤脚医生],"[赤脚医生, 和, 她, 的, 小, 背篓]",1,6,1,1.0,5.910618,0.0
332631,413349,2,0.0,情洒杏林路的赤脚医生,16088,[赤脚医生],"[情洒, 杏林, 路, 的, 赤脚医生]",1,5,1,1.0,3.940412,0.0
332632,413350,3,0.0,邯郸冀南新区赤脚医生补助名单正在审核中,16088,[赤脚医生],"[邯郸, 冀南, 新区, 赤脚医生, 补助, 名单, 正在, 审核, 中]",1,9,1,1.0,1.477655,0.0
332633,413351,3,0.0,疑似传播HIV病毒印度一名赤脚医生被捕,16088,[赤脚医生],"[疑似, 传播, HIV, 病毒, 印度, 一名, 赤脚医生, 被捕]",1,8,1,1.0,1.477655,0.0

In [39]:
# Feature: matched orders
def match_order_score(list1, list2):
    words_matched = []
    for j in list2:
        for i in list1:
            if j == i:
                words_matched.append(j)
#     print(words_matched)
    checkpoint1 = 0
    checkpoint2 = []
    from itertools import combinations, product
    checkpoint1 = list(combinations(list1, 2))
    for i in range(len(words_matched)):
        try:
            checkpoint2.append(tuple([words_matched[i], words_matched[i + 1]]))
        except:
            break

    matched_order = []
    for s in checkpoint1:
        for l in checkpoint2:
            if s == l:
                matched_order.append(1)
            else:
                matched_order.append(0)
    if matched_order == []:
        return 0
    else:
        return (matched_order.count(1) * 1. / len(matched_order))

In [40]:
link_match_order = []
for i in range(len(df)):
    link_match_order.append(match_order_score(df['qid_terms'][i], df['title_terms'][i]))
df['match_order_score'] = link_match_order

In [41]:
# df = df.drop(['index'], axis = 1)
df

,index,label,label_binary,title_clean,group_id,qid_terms,title_terms,num_qid_terms,num_title_terms,tot_num_matches,match_ratios,tfidf_score,match_density,match_order_score
0,0,5,1.0,G5京昆高速瓦厂坪大桥路段山体险情建议大家推迟出行,893,"[G5, 高速]","[G5, 京昆, 高速, 瓦厂, 坪, 大桥路, 段, 山体, 险情, 建议, 大家, 推迟...",2,13,2,1.0,1.685839,1.0,1.0
1,1,5,1.0,G5京昆高速雅西段拖乌山突降暴雪部分路段积雪深达1米,893,"[G5, 高速]","[G5, 京昆, 高速, 雅, 西段, 拖, 乌山, 突降, 暴雪, 部分, 路段, 积雪,...",2,15,2,1.0,1.685839,1.0,1.0
2,2,5,1.0,12月起G5京昆高速开始冬管这些地方需特别注意,893,"[G5, 高速]","[12, 月, 起, G5, 京昆, 高速, 开始, 冬管, 这些, 地方, 需, 特别, 注意]",2,13,2,1.0,1.854423,1.0,1.0
3,4,5,1.0,G5京昆高速因大雪路面结冰继续交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 因, 大雪, 路面, 结冰, 继续, 交通管制]",2,9,2,1.0,2.318028,1.0,1.0
4,5,5,1.0,G5京昆高速结冰严重栗子坪至彝海双向交通管制,893,"[G5, 高速]","[G5, 京昆, 高速, 结冰, 严重, 栗子, 坪, 至, 彝海, 双向, 交通管制]",2,11,2,1.0,2.060470,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332629,413347,3,0.0,还记得H7N9吗绍兴赤脚医生李兰娟领衔完成的项目获国家科技进步特等奖,16088,[赤脚医生],"[还, 记得, H7N9, 吗, 绍兴, 赤脚医生, 李兰娟, 领衔, 完成, 的, 项目,...",1,15,1,1.0,1.074658,0.0,0.0
332630,413348,2,0.0,赤脚医生和她的小背篓,16088,[赤脚医生],"[赤脚医生, 和, 她, 的, 小, 背篓]",1,6,1,1.0,5.910618,0.0,0.0
332631,413349,2,0.0,情洒杏林路的赤脚医生,16088,[赤脚医生],"[情洒, 杏林, 路, 的, 赤脚医生]",1,5,1,1.0,3.940412,0.0,0.0
332632,413350,3,0.0,邯郸冀南新区赤脚医生补助名单正在审核中,16088,[赤脚医生],"[邯郸, 冀南, 新区, 赤脚医生, 补助, 名单, 正在, 审核, 中]",1,9,1,1.0,1.477655,0.0,0.0
332633,413351,3,0.0,疑似传播HIV病毒印度一名赤脚医生被捕,16088,[赤脚医生],"[疑似, 传播, HIV, 病毒, 印度, 一名, 赤脚医生, 被捕]",1,8,1,1.0,1.477655,0.0,0.0

In [42]:
df[20:100]

,index,label,label_binary,title_clean,group_id,qid_terms,title_terms,num_qid_terms,num_title_terms,tot_num_matches,match_ratios,tfidf_score,match_density,match_order_score
20,30,1,0.0,农研站的猪打破了人类心脏病延续几十年的僵局,894,[GAGS],"[农研, 站, 的, 猪, 打破, 了, 人类, 心脏病, 延续, 几十年, 的, 僵局]",1,12,0,0.0,0.000000,0.0,0.0
21,31,1,0.0,更健康更饱满更加Q弹没皱纹一个成分让你重新做人,894,[GAGS],"[更, 健康, 更, 饱满, 更加, Q, 弹, 没, 皱纹, 一个, 成分, 让, 你, ...",1,14,0,0.0,0.000000,0.0,0.0
22,32,1,0.0,WAYWEI跟大家拜年2018年更年轻更美丽,894,[GAGS],"[WAYWEI, 跟, 大家, 拜年, 2018, 年, 更, 年轻, 更, 美丽]",1,10,0,0.0,0.000000,0.0,0.0
23,33,1,0.0,抗皱神药玻色因到底是个啥,894,[GAGS],"[抗皱, 神药, 玻色, 因, 到底, 是, 个, 啥]",1,8,0,0.0,0.000000,0.0,0.0
24,34,1,0.0,人体肠道微生物如何降解复杂多糖,894,[GAGS],"[人体, 肠道, 微生物, 如何, 降解, 复杂, 多糖]",1,7,0,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,136,2,0.0,GEC轻量级多国语言推广社区测试版发布,899,[GEC],"[GEC, 轻量级, 多, 国, 语言, 推广, 社区, 测试版, 发布]",1,9,1,1.0,1.707824,0.0,0.0
96,137,5,1.0,GEC币可能是下一个风口,899,[GEC],"[GEC, 币, 可能, 是, 下, 一个, 风口]",1,7,1,1.0,2.988692,0.0,0.0
97,138,5,1.0,GEC将在今晚开启崭新的一页,899,[GEC],"[GEC, 将, 在, 今晚, 开启, 崭新, 的, 一页]",1,8,1,1.0,2.390954,0.0,0.0
98,139,3,0.0,只要你有才每天都有GEC平台送给你云矿机的机会,899,[GEC],"[只要, 你, 有, 才, 每天, 都, 有, GEC, 平台, 送给, 你, 云, 矿机,...",1,15,1,1.0,1.707824,0.0,0.0
99,140,5,1.0,GEC给了币圈一次大的震荡,899,[GEC],"[GEC, 给, 了, 币, 圈, 一次, 大, 的, 震荡]",1,9,1,1.0,3.984923,0.0,0.0

In [43]:
data_after_extraction = df.drop(['label','index', 'title_clean', 'qid_terms','title_terms', 'num_qid_terms', 'num_title_terms'], axis = 1)
data_after_extraction

,label_binary,group_id,tot_num_matches,match_ratios,tfidf_score,match_density,match_order_score
0,1.0,893,2,1.0,1.685839,1.0,1.0
1,1.0,893,2,1.0,1.685839,1.0,1.0
2,1.0,893,2,1.0,1.854423,1.0,1.0
3,1.0,893,2,1.0,2.318028,1.0,1.0
4,1.0,893,2,1.0,2.060470,1.0,1.0
...,...,...,...,...,...,...,...
332629,0.0,16088,1,1.0,1.074658,0.0,0.0
332630,0.0,16088,1,1.0,5.910618,0.0,0.0
332631,0.0,16088,1,1.0,3.940412,0.0,0.0
332632,0.0,16088,1,1.0,1.477655,0.0,0.0
332633,0.0,16088,1,1.0,1.477655,0.0,0.0

In [128]:
data_after_extraction_sorted = data_after_extraction.sort_values(['group_id'], ascending = True)
data_after_extraction_sorted

,label_binary,group_id,tot_num_matches,match_ratios,tfidf_score,match_density,match_order_score
56412,1.0,1,2,0.50,2.053733,1.0,0.166667
56414,0.0,1,2,0.50,2.933904,1.0,0.166667
56413,1.0,1,2,0.50,2.567166,1.0,0.166667
56411,1.0,1,2,0.50,2.053733,1.0,0.166667
56410,1.0,1,3,0.75,1.705148,1.0,0.083333
...,...,...,...,...,...,...,...
47912,1.0,18381,0,0.00,0.000000,0.0,0.000000
47911,1.0,18381,0,0.00,0.000000,0.0,0.000000
47910,1.0,18381,0,0.00,0.000000,0.0,0.000000
47919,0.0,18381,0,0.00,0.000000,0.0,0.000000
47913,1.0,18381,0,0.00,0.000000,0.0,0.000000

In [129]:
Transformed_data = data_after_extraction_sorted
Transformed_data['label_binary'] = ['{:.0f}'.format(i) for i in Transformed_data['label_binary']]
Transformed_data['qid'] = ['qid:%i' % i for i in Transformed_data['group_id']]
Transformed_data['feature_1'] = ['1:{:.6f}'.format(i) for i in Transformed_data['tot_num_matches']]
Transformed_data['feature_2'] = ['2:{:.6f}'.format(i) for i in Transformed_data['match_ratios']]
Transformed_data['feature_3'] = ['3:{:.6f}'.format(i) for i in Transformed_data['tfidf_score']]
Transformed_data['feature_4'] = ['4:{:.6f}'.format(i) for i in Transformed_data['match_density']]
Transformed_data['feature_5'] = ['5:{:.6f}'.format(i) for i in Transformed_data['match_order_score']]
Transformed_data = Transformed_data.drop(['group_id', 'tot_num_matches', 'match_ratios', 'tfidf_score', 'match_density', 'match_order_score'], axis = 1)
Transformed_data = Transformed_data.reset_index(drop = True)
Transformed_data

,label_binary,qid,feature_1,feature_2,feature_3,feature_4,feature_5
0,1,qid:1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
1,0,qid:1,1:2.000000,2:0.500000,3:2.933904,4:1.000000,5:0.166667
2,1,qid:1,1:2.000000,2:0.500000,3:2.567166,4:1.000000,5:0.166667
3,1,qid:1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
4,1,qid:1,1:3.000000,2:0.750000,3:1.705148,4:1.000000,5:0.083333
...,...,...,...,...,...,...,...
332629,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
332630,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
332631,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
332632,0,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
332633,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [130]:
#shuffle the data
from sklearn.utils import shuffle
Transformed_data = shuffle(Transformed_data)
Transformed_data = Transformed_data.reset_index(drop = False)
Transformed_data

,index,label_binary,qid,feature_1,feature_2,feature_3,feature_4,feature_5
0,192817,0,qid:10637,1:3.000000,2:0.600000,3:3.510630,4:0.500000,5:0.100000
1,262653,0,qid:14553,1:2.000000,2:0.400000,3:0.000000,4:0.000000,5:0.000000
2,148012,0,qid:8187,1:1.000000,2:0.333333,3:1.793611,4:0.000000,5:0.000000
3,305507,1,qid:16902,1:2.000000,2:0.666667,3:1.957790,4:0.000000,5:0.333333
4,30178,0,qid:1591,1:1.000000,2:0.250000,3:1.970206,4:0.000000,5:0.000000
...,...,...,...,...,...,...,...,...
332629,241115,1,qid:13330,1:1.000000,2:1.000000,3:1.886790,4:0.000000,5:0.000000
332630,295972,0,qid:16381,1:1.000000,2:0.250000,3:0.813129,4:0.000000,5:0.000000
332631,285252,0,qid:15788,1:3.000000,2:0.500000,3:1.309211,4:1.000000,5:0.066667
332632,262423,1,qid:14538,1:1.000000,2:0.500000,3:1.011649,4:0.000000,5:0.000000
332633,133623,0,qid:7404,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [131]:
#Split the data
#Train: 9630/(9630+2874+2707) = 63.3
#Test: 2874/(9630+2874+2707) = 18.9
#vali: 2707/(9630+2874+2707) = 17.8
train_data = Transformed_data[:199580]
train_data = train_data.sort_values('index', ascending = True)
train_data

,index,label_binary,qid,feature_1,feature_2,feature_3,feature_4,feature_5
19128,0,1,qid:1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
40407,3,1,qid:1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
156931,4,1,qid:1,1:3.000000,2:0.750000,3:1.705148,4:1.000000,5:0.083333
65947,5,1,qid:1,1:2.000000,2:0.500000,3:1.711444,4:1.000000,5:0.166667
135038,6,1,qid:1,1:3.000000,2:0.750000,3:2.131435,4:1.000000,5:0.083333
...,...,...,...,...,...,...,...,...
68008,332625,1,qid:18381,1:1.000000,2:0.500000,3:2.507369,4:0.000000,5:0.000000
171209,332627,0,qid:18381,1:1.000000,2:0.500000,3:3.343159,4:0.000000,5:0.000000
53039,332628,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
26386,332630,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
184305,332633,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [138]:
# train_data = train_data.drop(['index'], axis = 1)
np.savetxt(r"train_data_mine.txt", train_data.values, fmt = '%s')

In [141]:
feats = train_data.drop(['qid'], axis = 1)
feats

,label_binary,feature_1,feature_2,feature_3,feature_4,feature_5
19128,1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
40407,1,1:2.000000,2:0.500000,3:2.053733,4:1.000000,5:0.166667
156931,1,1:3.000000,2:0.750000,3:1.705148,4:1.000000,5:0.083333
65947,1,1:2.000000,2:0.500000,3:1.711444,4:1.000000,5:0.166667
135038,1,1:3.000000,2:0.750000,3:2.131435,4:1.000000,5:0.083333
...,...,...,...,...,...,...
68008,1,1:1.000000,2:0.500000,3:2.507369,4:0.000000,5:0.000000
171209,0,1:1.000000,2:0.500000,3:3.343159,4:0.000000,5:0.000000
53039,1,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
26386,1,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
184305,1,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [142]:
np.savetxt(r"feats_mine.txt", feats.values, fmt = '%s')

In [133]:
test_data = Transformed_data[199580:266107]
test_data = test_data.sort_values('index', ascending = True)
test_data

,index,label_binary,qid,feature_1,feature_2,feature_3,feature_4,feature_5
212697,2,1,qid:1,1:2.000000,2:0.500000,3:2.567166,4:1.000000,5:0.166667
207138,18,0,qid:1,1:4.000000,2:1.000000,3:3.105434,4:0.666667,5:0.111111
247867,20,1,qid:1,1:2.000000,2:0.500000,3:2.281925,4:1.000000,5:0.166667
250648,21,0,qid:1,1:4.000000,2:1.000000,3:2.846648,4:0.666667,5:0.111111
264407,29,0,qid:2,1:3.000000,2:1.000000,3:1.653749,4:0.500000,5:0.333333
...,...,...,...,...,...,...,...,...
215590,332606,0,qid:18379,1:2.000000,2:0.500000,3:1.328308,4:1.000000,5:0.166667
200429,332607,0,qid:18380,1:2.000000,2:0.666667,3:1.086797,4:1.000000,5:0.333333
208035,332610,0,qid:18380,1:2.000000,2:0.666667,3:1.195477,4:1.000000,5:0.333333
212931,332629,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
265488,332631,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [139]:
test_data = test_data.drop(['index'], axis = 1)
np.savetxt(r"test_data_mine.txt", test_data.values, fmt = '%s')

In [135]:
vali_data = Transformed_data[266107:332635]
vali_data = vali_data.sort_values('index', ascending = True)
vali_data

,index,label_binary,qid,feature_1,feature_2,feature_3,feature_4,feature_5
269552,1,0,qid:1,1:2.000000,2:0.500000,3:2.933904,4:1.000000,5:0.166667
285689,10,1,qid:1,1:2.000000,2:0.500000,3:2.567166,4:1.000000,5:0.166667
297963,16,1,qid:1,1:2.000000,2:0.500000,3:1.867030,4:0.000000,5:0.000000
285661,31,0,qid:2,1:3.000000,2:1.000000,3:1.954431,4:0.500000,5:0.166667
323426,33,0,qid:2,1:1.000000,2:0.333333,3:1.363424,4:0.000000,5:0.000000
...,...,...,...,...,...,...,...,...
269956,332616,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
288718,332618,1,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000
328506,332622,1,qid:18381,1:2.000000,2:1.000000,3:1.648554,4:1.000000,5:1.000000
308725,332626,0,qid:18381,1:1.000000,2:0.500000,3:2.005895,4:0.000000,5:0.000000
280482,332632,0,qid:18381,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:0.000000

In [140]:
vali_data = vali_data.drop(['index'], axis = 1)
np.savetxt(r"vali_data_mine.txt", vali_data.values, fmt = '%s')

In [73]:
group_id_count = data_after_extraction_sorted.groupby('group_id')['group_id'].count()
group_id_count = pd.DataFrame(group_id_count).rename(columns = {'group_id': 'counts'})
group_id_count

          counts
group_id
1             25
2             25
3              9
4             26
5             20
...          ...
18377          1
18378         27
18379         22
18380          8
18381         19

[18381 rows x 1 columns]

In [74]:
group_id_count.to_csv('group', index = False)

# Model Set-up

In [45]:
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer, load_boston, load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import mean_squared_error, roc_auc_score, precision_score

In [47]:
df_1 = data_after_extraction.drop(['label_binary', 'group_id'], axis = 1)
Y_1 = data_after_extraction['label_binary']
df_1, Y_1

(        tot_num_matches  match_ratios  tfidf_score  match_density  \
 0                     2           1.0     1.685839            1.0
 1                     2           1.0     1.685839            1.0
 2                     2           1.0     1.854423            1.0
 3                     2           1.0     2.318028            1.0
 4                     2           1.0     2.060470            1.0
 ...                 ...           ...          ...            ...
 332629                1           1.0     1.074658            0.0
 332630                1           1.0     5.910618            0.0
 332631                1           1.0     3.940412            0.0
 332632                1           1.0     1.477655            0.0
 332633                1           1.0     1.477655            0.0

         match_order_score
 0                     1.0
 1                     1.0
 2                     1.0
 3                     1.0
 4                     1.0
 ...                   ...
 332629                0.0
 332630                0.0
 332631                0.0
 332632                0.0
 332633                0.0

 [332634 rows x 5 columns],
 0         1.0
 1         1.0
 2         1.0
 3         1.0
 4         1.0
          ...
 332629    0.0
 332630    0.0
 332631    0.0
 332632    0.0
 332633    0.0
 Name: label_binary, Length: 332634, dtype: float64)

In [48]:
# #Scaling using the Standard Scaler
sc_1 = StandardScaler()
sc_1.fit(df_1)
X_1 = pd.DataFrame(sc_1.fit_transform(df_1))
X_1

               0         1         2         3         4
0       0.187795  0.947654 -0.104860  1.216618  2.473978
1       0.187795  0.947654 -0.104860  1.216618  2.473978
2       0.187795  0.947654  0.012473  1.216618  2.473978
3       0.187795  0.947654  0.335141  1.216618  2.473978
4       0.187795  0.947654  0.155881  1.216618  2.473978
...          ...       ...       ...       ...       ...
332629 -0.581352  0.947654 -0.530239 -0.900349 -0.605943
332630 -0.581352  0.947654  2.835565 -0.900349 -0.605943
332631 -0.581352  0.947654  1.464312 -0.900349 -0.605943
332632 -0.581352  0.947654 -0.249755 -0.900349 -0.605943
332633 -0.581352  0.947654 -0.249755 -0.900349 -0.605943

[332634 rows x 5 columns]

In [49]:
#train-test-split
X_train, X_test, y_train, y_test = train_test_split(df_1, Y_1, test_size=0.2, random_state=0)

In [50]:
#Converting the dataset in proper LGB format
d_train = lgb.Dataset(X_train, label = y_train)

In [51]:
#setting up the prarmeters
params = {}
params['learning_rate'] = 0.1
params['boosting_type'] = 'gbdt' # GradientBoostingDecisionTree
params['objective'] = 'binary' #Multi-class target feature
params['metric'] = 'binary_logloss' #metric for multi-class
params['max_depth'] = 30
params['num_leaves'] = 16 #no.of unique values in the target class not inclusive of the end value

In [52]:
# trainning the model
clf = lgb.train(params, d_train, 100) #targeting the model on 100 epocs

In [53]:
#prediction on the test dataset
y_pred_1 = clf.predict(X_test)

In [54]:
#printing the predctions
y_pred_1

array([0.55668748, 0.27515914, 0.72132285, ..., 0.27515914, 0.2982605 ,
       0.54633117])

In [55]:
#argmax() method
# y_pred_2 = [np.argmax(line) for line in y_pred_1]
# #printing the predictions
# print(y_pred_2)
y_pred_1 = y_pred_1.round(0)
y_pred_1 = y_pred_1.astype(int)
print(roc_auc_score(y_pred_1, y_test)) #0.965424739195231
print(y_pred_1[0:5])

0.6556588989221463
[1 0 1 0 0]

In [56]:
# #using precision score for error metrics
# prec_score = precision_score(y_pred_2, y_test, average=None).mean()
# print(prec_score)

In [57]:
#using RMSE error metric
RMSE = np.sqrt(mean_squared_error(y_pred_1, y_test))
print(RMSE)

0.5831315364517216